language: bash
services: docker

env:
  - VERSION=latest

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="yongjhih/pokemon-go-mitm:$VERSION"
  - dockerdir="${DOCKERDIR:-.}"

script:
  - docker build -t "$image" "$dockerdir"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
